name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run nvm install 10
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn --frozen-lockfile
      - run: yarn test
